workflows:
  android-workflow:
    name: Build APK
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      java: 17
    scripts:
      - name: Build Debug APK
        script: |
          chmod +x gradlew
          ./gradlew :admob:assembleDebug --stacktrace
    artifacts:
      - "**/*.apk"
